const layoutPropNames = [
  'layout',
  'inline',
  'vertical',
  'horizontal',
  'reverse',
  'start',
  'center',
  'end',
  'stretch',
  'baseline',
  'centered',
  'selfStart',
  'selfCenter',
  'selfEnd',
  'selfStretch',
  'selfBaseline',
  'justifyStart',
  'justifyEnd',
  'justifyCenter',
  'justifyBetween',
  'justifyAround',
  'wrap',
]

export default layoutPropNames